apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "5s"

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: fraud_detection
    user: fraud_user
    secureJsonData:
      password: fraud_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
